# Generated by Django 5.0.2 on 2025-03-13 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_image', models.ImageField(upload_to='templates/')),
                ('name_x', models.IntegerField(default=0, help_text='X coordinate for name placement')),
                ('name_y', models.IntegerField(default=0, help_text='Y coordinate for name placement')),
                ('course_x', models.IntegerField(default=0, help_text='X coordinate for course placement')),
                ('course_y', models.IntegerField(default=0, help_text='Y coordinate for course placement')),
                ('date_x', models.IntegerField(default=0, help_text='X coordinate for date placement')),
                ('date_y', models.IntegerField(default=0, help_text='Y coordinate for date placement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('certificate_pdf', models.FileField(upload_to='certificates/')),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartDocsHubApp.certificatetemplate')),
            ],
        ),
    ]
